"""
Breakout-population backtest.

Addresses a selection-bias problem: the exit parameters were previously tuned on
the 13 real closed trades, but 11 of those 12 symbols fail the new screener. That
population is being deliberately eliminated, so tuning on it optimises for a
distribution that will not exist going forward.

This replays entries generated by the ACTUAL breakout logic from
technical_screener.check_technical_breakout() (close > SMA50, volume >= 1.5x
50-day average, close >= 95% of the 252-day high) over 3 years of names that pass
the NEW fundamental screen — i.e. the population the bot will actually trade.

Daily bars only (FMP caps intraday history), so this is used to answer the
multi-day, population-dependent questions: the profit ladder, the time lever and
the power-hold rule. The intraday-pullback decision stays with the 5-minute
analysis, where it can be modelled faithfully.
"""
import statistics, datetime

from bardata import daily as _daily_from_parquet

START, END = "2023-07-01", "2026-08-04"

SMA_WINDOW, VOL_WINDOW, VOL_SURGE = 50, 50, 1.50
ROLL_HIGH, PIVOT_PROX, MIN_HIST = 252, 0.95, 50
COOLDOWN_DAYS = 20          # don't re-enter the same name immediately
BASE_STOP = 0.07
EMA_W, EMA_BUF = 21, 0.01
PH_GAIN, PH_TRIG, PH_DUR = 20.0, 21, 56


def daily(sym):
    """Daily bars from the committed benchmark dataset — no network, no rate limit.

    Previously this fetched from FMP and cached to data/hist_{sym}.json, which made
    every benchmark run slow, throttled, and non-reproducible. The dataset is now
    committed under benchmark_data/; see research/fetch_daily.py to extend it.
    """
    d = _daily_from_parquet(sym)
    if not d or len(d) < 300:
        return None
    return sorted(d, key=lambda r: r["date"])


def indicators(d):
    closes = [r["close"] for r in d]
    vols = [r["volume"] for r in d]
    highs = [r["high"] for r in d]
    n = len(d)
    sma = [None] * n
    avgv = [None] * n
    rh = [None] * n
    ema = [None] * n
    k = 2 / (EMA_W + 1)
    for i in range(n):
        if i >= SMA_WINDOW - 1:
            sma[i] = sum(closes[i - SMA_WINDOW + 1:i + 1]) / SMA_WINDOW
        if i >= VOL_WINDOW - 1:
            avgv[i] = sum(vols[i - VOL_WINDOW + 1:i + 1]) / VOL_WINDOW
        if i >= MIN_HIST - 1:
            rh[i] = max(highs[max(0, i - ROLL_HIGH + 1):i + 1])
        ema[i] = closes[i] if i == 0 else closes[i] * k + ema[i - 1] * (1 - k)
    return sma, avgv, rh, ema


def find_breakouts(d):
    sma, avgv, rh, _ = indicators(d)
    out, last = [], -10**9
    for i in range(len(d)):
        if sma[i] is None or avgv[i] is None or rh[i] is None or not avgv[i]:
            continue
        if i - last < COOLDOWN_DAYS or i + 1 >= len(d):
            continue
        c, v = d[i]["close"], d[i]["volume"]
        if c > sma[i] and v / avgv[i] >= VOL_SURGE and c >= rh[i] * PIVOT_PROX:
            out.append(i)
            last = i
    return out


def dyn_trail(cfg, unreal, cal_days, cur):
    cands = []
    for th, pct in cfg["profit_tiers"]:
        if unreal >= th:
            cands.append(pct); break
    for th, pct in cfg["time_tiers"]:
        if cal_days >= th:
            cands.append(pct); break
    if not cands:
        return None
    new = min(cands)
    return new if new < cur else None


def sim_trade(cfg, d, ema, i_sig):
    """Enter at the open the day after the signal; exit per cfg on daily bars."""
    e = i_sig + 1
    entry = d[e]["open"]
    if not entry:
        return None
    peak, trail = entry, cfg.get('base_stop', BASE_STOP)
    last_peak_j = e
    run_high = 0.0
    peak_gain = 0.0
    ph = False
    d0 = datetime.date.fromisoformat(d[e]["date"][:10])

    for j in range(e, len(d)):
        bar = d[j]
        held = j - e
        cal = (datetime.date.fromisoformat(bar["date"][:10]) - d0).days

        if bar["high"] > peak:
            last_peak_j = j
        peak = max(peak, bar["high"])
        peak_gain = max(peak_gain, (peak / entry - 1) * 100)
        if cfg["power_hold"]:
            if peak_gain >= PH_GAIN and cal <= PH_TRIG:
                ph = True
            if ph and cal > PH_DUR:
                ph = False

        # resting trailing stop can fill intra-day
        lvl = peak * (1 - trail)
        if bar["low"] <= lvl:
            return (lvl / entry - 1) * 100, held, "trail"

        c = bar["close"]
        nt = dyn_trail(cfg, (c / entry - 1) * 100, cal, trail)
        if nt:
            trail = nt

        # daily proxy for the Intraday Loss Minimiser (optional)
        if cfg["minimiser"] and held >= 2 and not ph:
            run_high = max(run_high, c)
            if run_high >= entry * 0.995 and c <= run_high * (1 - cfg["minimiser"]):
                return (c / entry - 1) * 100, held, "minimiser"

        stale = cfg.get('stale')
        if stale and not ph and (j - last_peak_j) >= stale and held >= 7:
            return (c / entry - 1) * 100, held, "stale"

        if cfg.get('ema', True) and held >= 7 and not ph and ema[j] and c < ema[j] * (1 - EMA_BUF):
            return (c / entry - 1) * 100, held, "ema"

    last = d[-1]
    return (last["close"] / entry - 1) * 100, len(d) - 1 - e, "open"


def run(cfg, universe):
    res = []
    for sym in universe:
        d = daily(sym)
        if not d:
            continue
        _, _, _, ema = indicators(d)
        for i in find_breakouts(d):
            r = sim_trade(cfg, d, ema, i)
            if r:
                res.append(r)
    return res


def report(res, label):
    pcts = [r[0] for r in res]
    w = [p for p in pcts if p > 0]
    l = [p for p in pcts if p <= 0]
    aw = statistics.mean(w) if w else 0
    al = statistics.mean(l) if l else 0
    payoff = aw / abs(al) if al else float("inf")
    big = 100 * sum(1 for p in pcts if p >= 20) / len(pcts)
    print(f"{label:52}{len(pcts):>6}{statistics.mean(pcts):>+9.2f}{100*len(w)/len(pcts):>7.0f}%"
          f"{aw:>+8.2f}{al:>+8.2f}{payoff:>8.2f}{big:>8.1f}%{statistics.mean([r[1] for r in res]):>7.0f}")
    return statistics.mean(pcts)
